---
title: Unafahamu Nini Kulihusu Kanisa?
author: Kalunde
date: '2019-08-13'
slug: je-unafahamu-nini-kulihusu-kanisa
categories: []
tags: []
---

Nikukaribishe tena Ewe mgeni na Mwenyeji kwa kutembelea na kusoma kurasa katika tovoti yetu.Tulijaribu kwa miongo mingi kukaa kimya, lakini sasa tunahisi kwamba kila kitu kinaweza kusemwa juu ya kile tulipaswa kusema. Naona mwili wangu unataka kusema, kila mahali maungoni mwangu kuna usemi maalumu kwa ajili ya kanisa. Ninathubutu kusema kile ambacho nadhani sipaswi kukizuia, si tu nasema ninachofikiri bali zaidi sana ni kile ninachokiona ulimwengu wa mwili na ulimwengu wa Roho.

### KANISA JINSI LILIVYO
Nimeona kuwa, mawazo yetu mazuri juu ya kanisa na mienendo yetu ya kiroho haitupi nafasi kabisa kuliona kanisa jinsi liliyo. vile kanisa lilivyo leo, ndivyo lilivyo. Imani na mitizamo yetu ya kiroho isitufanye tulitizame kanisa kinyume cha vile lilivyo. Na wala jamii ya waamini Mungu Duniani mote hawawezi kuenda zaidi ya kanisa lilipofikia. Ni muhimu kukubaliana na hali halisi tena ni hatua ya uaminifu kuutambua na kuukubali udhaifu unaotukabali kama kanisa. 

Karibu tuunene ukweli unatotuhusu, tuzungumze kwa *uyakinifu* katika uhuru na nia njema, kanisa lilivyo ni muhimu kwa namna yoyote. Ikiwa kuna **upungufu**, basi na tujuwe wazi kwamba uwajibikaji wa kimakusudi unahitajika, lakini ikiwa kuna **utimilifu** basi utukufu wa Mungu utaenea ulimwenguni mote. Kujaribu kuipoteza hali yoyote kati ya mbili hizi (upungufu na utimilifu) kiimani haitakosa kuchukuliwa kama uhalifu wa kiroho, na matokeo yake ni kushughulika nje ya tulichopaswa kukishughulikia, kwa kuwa ni shughuli nje ya lengo la kikanisa. 

Je, tunaweza kujisikia vibaya tukijua jinsi kanisa letu lilivyo? Na hasa mtu mwingine pengine tusiyemkubali anapojaribu kwa bidii kugusa maeneo yote ambayo ndiyo yaliyokuwa ya kipekee katika msingi wa imani yetu. Lakini, kwa upande mwingine unaweza kuona wazi kwamba kuna watu wengi wanaojaribu kutufanya tujisikie vizuri ndani ya kipindi cha matengenezo ya kikanisa, na tena yaonesha kwamba wako watu wanaojihusisha nasi kihisia wanaotujali na wanao jali pengine kila kitu kinachojaribu kutuondelea furaha yetu ya wokovu! ni sawa.

Pengine wote hawa tungaliweza kuwaita ni watumishi, wametumwa na inaweza kuwa mapema ikiwa tutahoji kuwa wametumwa na nani? Na tena niseme kweli, kujisikia kwetu vizuri kumekuwa ni kwa kitambo tu, hata inalazimika mara kwa mara watu hawa watu hawa watuzungukie ili tuendelee kijisikia vizuri ndani ya vipindi vyetu vya maumivu visivyokoma.

Biblia inasema *"msiwasikilize hao manabii wawaambiayo kwamaba mabaya hayatawapata---Yer 27:14,15"*. Si shida kanisa kuwa vile lilivyo, bali ni shida kubwa kutokujua hali inayolikabili kanisa, na tena ni hatari kutokujua vile tulivyopaswa kujua kulihusu kanisa. Tunaweza kukutana na Injili nzuri zinatotubariki, lakini kitendo cha injili hizo kutokutuwezesha kulijua kanisa lilivyo, kunaifanya injili ya namna hiyo kutokuwa na maana kabisa. 

Na tena shughuli yoyote inayomhusu Mungu kulihusu kanisa, hushughulika nalo tangu vile lilivyo mpaka vile lipaswavyo kuwa. Hivi lilivyo ni muhimu sana kwa ajili ya Mungu ili kulifanya liwe vile atakavyo na vile lipaswavyo kuwa. Mchango wetu katika kazi hii ni vile tutakavyo ruhusu kwa kuikubali gharama ya matengenezo yake, ambayo ni pamoja na kuupokea uharibifu wa kimungu ndani ya mienendo yetu ya kidini. Upungufu mwingi na udhaifu tulionao hiyo yaweza kuwa sababu ya chochote chema katika maisha ya kikanisa, ikiwa tutakuwa tayari na katika roho ya unyenyekevu katika kuyapokea mapinduzi ya kiroho katika mifumo yetu. 

### Kanisa ni nini?
Ni vema tukifahamu maana halisi ya kanisa! Kanisa ni mfumo mwema uliobeba maisha ya kiuadilifu kwa ajili ya ulimwengu, wala kanisa siyo mkusanyiko wa watu wanaolitii tu jina la Yesu. Au kama wengine wasemao kuwa kanisa ni mahali pa kuabudia. Huu ni wakati muhimu kwa sisi kuhakiki juu ya maelezo na tafsiri zinazo lihusu kanisa. Lugha yenye mafumbo hujaribu kuonesha kuwa <u> kanisa ni mwili wa Yesu </u>. Haitoshi kabisa kuwaambia watu hivyo bila ufunuo wa kweli na fasiri zinazoweza kueleweka. Maana pia makanisani mwetu huwa tunalo tukio moja maarufu. Mtumishi huchukua mkate tulionunua sehemu fulani na kuumega, akinukuuu toka maandiko yaliyoonesha tukio kama hilo hilo na kusema *Bwana Yesu usiku ule aliotolewa alitwaa makate---1 Kor 11:23--24*. 

Hii haikuwa siku ya kwanza ya Yesu kushiriki Pasaka bali ilikuwa siku ya mwisho. Yesu hakuwahi kuwaambia meneno hayo katika Pasaka nyingine za kiyahudi alizokula. Kisha mtumishi huendelea *fanyeni hivi kwa kunikumbuka*. Tukio hilo---yaani kuula mwili wa Yesu na kauli zake zilizua mzozo mkubwa sana kwa Wayahudi na wanafunzi wake. Hii inathibitishwa katika maandiko ya Biblia kuwa *"Wayahudi walinung'unika kwa sababu Yesu aliwaambia kuwa mwili wake ni chakula kilichoshuka kutoka mbinguni.  Basi Wayahudi walishindana wao kwa wao wakisema, Awezaje mtu huyu kutupa sisi mwili wake ili tuule?"---Yoh. 6:42,52*. Maandiko haya yanaonyesha kuwa jambo la kuula mwili wa Yesu lilikuwa gumu sana kwa wahayahudi, bali leo limekuwa rahisi sana kwa wakristo! Na sijui ni nani na kwa nini aliyarahisisha maudhui haya?

Lakini si Wayahudi tu, bali watu wengi miongoni mwa wanafunzi wake waliposikia, wakasema *"neno hili ni gumu, ni nani awezae kusikiliza?---Yoh 6:60"*. Hii inaonyesha kuwa liliwakwaza! Yesu akawajibu wote kwamba *"...Amin, amin, nawaambieni, Msipoula mwili wake Mwana wa Adamu na kuinywa damu yake, <u>hamna uzima ndani yenu</u>---Yoh 6:53"*. Leo imekuwaje rahisi? Kwani ilikuwa ni vigumu kula makate na kunywa divai kiasi cha kuhatarisha mahusiano? Je, huo mwili waliopewa ndiyo tunataka kuuzungumzia kama kanisa? Hebu tuangalie maandiko mengine, Paulo alisema *"mtu ajihoji mwenyewe, na hivyo aule mkate, na kukinywea kikombe. Maana alaye na kunywa, hula na kunywa hukumu ya nafsi yake, <u>kwa kutokuupambanua ule mwili</u>"---1 Kor 11:28-29*.

Mimi nadhani Wayahudi walikuwa na akili sana, kumbe haya ni mambo yaliyobeba hukumu, lakini tumeupambanuaje mwili sisi tunaokula mkate? Twaweza kusoma maandiko mengine ili yatusaidie kupambanua kati ya hiki na kile? Lakini ni upi mwili wa Yesu, ni ule mkate au ni lile kanisa? Pasaka ilikuwa inaliwa toka Misri, dhabihu na sadaka zinahistoria ndefu sana kabla ya kristo, lakini kinachoonekana ni kwamba, hapakuwa na suruhu, na sababu yanenewa kuwa;

> *"Roho Mtakatifu akionyesha neno hili, ya kwamba njia ya kupaingia patakatifu ilikuwa haijadhihirishwa bado, hapo hema ya kwanza ilipokuwa ingali ikisimama"---Ebr 9:8*

Dhabihu na toleo hukutaka, <u>lakini mwili</u> ulimweka tayari. Kwani kuna tofauti kati ya mkate ule alioumega na ile iliyokuwa inamegwa kwa desturi ya wayahudi tangu misri? Biblia yasema *"Na pasaka ya Wayahudi ilikuwa karibu; naye Yesu akakwea mpaka Yerusalemu"---Yoh 2:13*. Hii ndiyo pasaka iliyoanza Misri. Tukinena kwamba katika kuyatimiza mapenzi ya Mungu yaliyokuwa yameshindikana, ukatolewa mwili wa Yesu, je, yamaanisha ule makate?  Hapana, hapana kabisa, Ule mwili ulikuwa dhabihu iliyotolewa mara moja tu [*Ebr 10:14*], ikatosha, na Roho Mtakatifu ikiwa shahidi wa haya [*Ebr 10:15*] na baada ya hapo, hapana tena toleo kwa ajili ya dhambi. Lakini swali muhimu la kujiuliza ni *mwili wa Yesu ni upi---kanisa au ni ule mkate?*

Biblia inasema *"Na tujitahidi kuuhifadhi umoja wa Roho katika kifungo cha imani. Mwili mmoja, na Roho mmoja, kam na mlivyoitwa katika tumaini moja, imani moja, ubatizo mmoja, Mungu mmoja"---Efe. 4:3-5*. Paulo anaendelea kusema *"Naye alitoa wengine kuwa mitume, na wengine kuwa manabii; na wengine kuwa wainjilisti na wengine kuwa wachungaji na waalimu;  kwa kusudi la kuwakamilisha watakatifu, hata kazi ya huduma itendeke, <u>hata mwili wa Kristo ujengwe</u>"---Efe. 4:11-12*. Mimi ninautafuta huu mwili unaojengwa, maana ni wa ghali kuliko ile mikate na divai tuinywayo. Kusudio ni kanisa, hizo lugha nyingine za kitamathali zisitupotezee shabaha yetu. Kukosa kujua ni mwili upi uliokuwa ukimaanishwa, huko ni kukosa upambanufu na kusababisha mgongano wa kimaandiko na kiimani. 

Biblia tena yasema *"katika yeye mwili wote ukiungamanishwa na kushikamanishwa kwa msaada wa kila kiungo, kwa kadri ya utendaji wa kila sehemu"*. Hebu nionesheni utendaji wa kila sehemu katika kuungamnishwa ule makate tuulao, hebu nionesheni enyi wanazuoni wa leo namna vile ule mkate tuulao unavyojijenga wenyewe. Lakini pia hebu nionesheni vile Yesu alivyotoa mkate msalabani badala ya mwili wake, kuwa sadaka na dhabihu. Tunaitumikia mikate kwa kisingizio imeandikwa huku tukiuvunja vunja mwili wa Yesu ambao ndiyo kanisa lake! Tunakuwaje na uzima wa milele kwa kula mikate huku tukiacha ushirika wa Rohoni? Kwani uzima wa milele ni nini? Biblia inasema *"Na uzima wa milele ni huu, wakujue wewe, Mungu wa pekee wa kweli, na Yesu Kristo uliyemtuma"---Yoh. 17:3*. Je, hii haimanishi kuwa uzima wa milele ni ujuzi wa Rohoni juu ya Yesu na Mungu? Tunamjuaje Yesu na Mungu kwa kula mikate? Je hamna nyumba ya za kulia hiyo mikate yenu, huku mkiukhalifu msingi wa mkate? [*1 Kor 11:22*]. Biblia inatoa onyo kali kuwa yeye asemaye anamjua Mungu naye hazishiki amri zake kuwa ni mwongo na kweli haimo ndani yake [*1 Yoh. 2:4*].  Je tutaacha kuzishika amri na kula mikate ili tuwe na uzima wa milele?  kwa lugha nyingine uzima wa milele ni kuzishika amri. 

Ni nani ambaye hajala? Na tena yakoje maisha ya wala mikate kwa imani? Mimi sisemi tusile ikiwa imani yako ni kula, hakikisha tu kwamba kula kwako hakuondowi msingi wetu katika kristo wala hakutukwepeshi na wajibu utupasao. Hakuna shida kula lakini shida ni pale utakopkosa upambanufu wa hicho ukilacho, basi meza yetu itageuka na kuwa meza ya mtego [*Rum 11:9; Zab 69:22--23*] na kuwa ibada ya sanamu. Mimi nimetumwa niseme kulihusu kanisa, hilo likisimama vyema, mikate na wine  havina shida tena, bali kitakuwa chakula cha ushirika na twaweza kula chochote kwa pamoja kama familia huku tukiya tafsiri mafumbo ya kinabii yaliyobeba ujumbe kutuhusu. 

Maana hata hiyo pasaka Biblia husema Agano la kwanza lilikuwa ni kizuri cha mema yatakayokuwa, wala si mambo yenyewe. Na Yesu alikula pasaka kama kawaiday ya Wayahudi wote, lakini alipojaribu kuwatafsiria waliochokuwa wanakila bila ujuzi, kesi yake ilikuwa ngumu akakabiliwa na hali kama vili nami nitrajiavyo kukabiliwa katika waraka huu. Yesu alichokoza dini za watu, maana haikuandikwa kwamba kile wakilacho kila mwaka ni mwili wa mtu au ni lugha iliyouhusu mwili wa mtu mmoja kutoka Nazarethi. 

Mimi sijaribu kuondoa maana ya fumbo lilolobebwa katika mkate na divai, bali naleta tafsiri yake ya wazi. Lakini hata Agano la Kale limejaribu kufafanua kwa sehemu kuhusu divai yenyewe lasema; *"ukanywa divai, damu ya mizabibu"---Kum 32:14*. Yesu pia aliwaambia Wayahudi *"Amini, amini, nawaambieni, Siye Musa aliyewapa chakula kile cha mbinguni, bali Baba yangu anawapa ninyi chakula cha kweli kitokacho mbinguni"---Yoh. 6:32*. Kauli hii inonesha uwepo wa chakula bora kuliko mana, lakini pia kauli hii inonesha Wayahudi hawakuwahi kupewa chakula cha kwel. Wote twajua kuwa ile mikate iliandaliwa nyumbani, na pengine hii mikate tunainunua dukani. Lakini zaidi, inawezekanaje Bwana Yesu kuwapa kile kile walichopewa toka mababu kuwa ndicho chakula cha kweli kutoka mbinguni?

Lakini chakula cha Mungu ni kile kishukacho kutoka mbinguni [*Yoh. 6:33*], lakini pia haitoshi tu kushuka kutoka mbinguni, maana hata ile mana ilishuka kutoka mbinguni. Upekee wa chakula hiki ni kwamba kina uwezo wa <u>kuupa ulimwengu uzima</u>, na si kulipa kanisa uzima [*Efe. 3:5--{6}*. Sasa niambie kiasi cha uzima licha ya ulimwengu, bali kwa kanisa unaloshiriki meza ya Bwana! Wayahudi wakamwambia Yesu siku zote utupe chakula hiki, Yesu akawaambia, mimi ndimi chakula cha uzima, yeye ajae kwangu hataona njaa kabisa, yeye aniaminiye hataona ki kamwe [*Yoh. 6:34--36*]. 

Basi Yesu ni nani na sisi ni nani?  Maandiko mengi katika kitabu kitakatifu yanathibitisha Yesu ni nani. Yesu mwenyewe alisema mimi ni mzabibu wa  kweli na Baba yangu ndiye mkulima [*Yoh. 15:1*], mimi ni mzabibu, ninyi ni matawi [*"Yoh. 15:5*], Kaendi ndani yangu nami ndani yenu [*"Yoh. 15:4"*]. Kama Yesu ni mzaituni, je, ni sehemu ipi ya mzaituni inayoliwa? na chakula hicho ni kipi? Bwana Yesu aliweka wazi pale aliposema chakula changu ndicho hiki, niyatende mapenzi yake aliyenipeleka, nikaimalize kazi yake [*Yoh. 4:34*]. Na mapenzi ya Mungu ni kutakaswa kwenu, mwepukane na uasherati [*1 Thes. 4:3*].

Hii humaanisha tu kwamba <br>utakatifu ndiyo matunda</br> ya kazi ya msalaba [*Gal. 5:22-24*], na mtakatifu ndio mti wa uzima uliokuwa ukilindwa. Na wala agizo la kwanza juu ya chakula, halizungumzi chochote juu ya ngano na wanyama bali Bwana Mungu alisema; *"...nimewapa kila mche utoao mbegu, ulio juu ya uso wa nchi yote pia, na kila mti ambao matunda yake yana mbegu (yaani uzao), vitakuwa ndivyo chakula chenu, na chkula cha kila mnyama wa nchi, na cha kila ndege wa angani , na cha kila kiut kitambaacho juu ya nchi, chenye uhai; majani yote ya miche, ndiyo chakula chenu"---Mwa. 1:29--30*. Na katika ule mzabibu tunaweza kuona dhana ya mwili wa Yesu na ikiwa sisi tunakaa ndani yake, unaliwaje mwili wa Yesu nasi tusiliwe? Na ikiwa sisi ni viungo vya mwili wake, waliwaje mwili wake na sisi tusiliwe? Je tunalika? Je, kipo kitu kwetu kimfaacho yoyote kwa chakula? 

Ukweli unaolihusu kanisa ni lazima uzingatie vile lilivyo na uzidi kuthibitisha zaidi undani wa vile kanisa lilivyo. Haitoshi tu kuliwazia kanisa vizuri bila kuchukua hakuta za kimakusudi katika kuhakikisha kwamba halijengwi nje ya muundo wake wa asili. Maana haliwezi kuwa zuri ikiwa haliishi vizuri, ni lazima uzuri wa kanisa utokane na maisha sahihi ya viungo vya mwili wake. Kuogopa na kutopenda kijua hali ya kanisa ni kuukimbia tu ukweli usioepukika, na kuhuzunika na kuchukia ikiwa hali za kikanisa zinfichuliwa na ukweli fulani, huko ni kujaribu kuzuia shughuli muhimu inayotuhusu na kuusukumia mbali ukweli. 

Mara zote tungalipenda kama wanadamu, ikiwa mtu mwingine anatusifu na kuitambua mitazamo yetu, anajali na anaziwajibbkia hisia zetu kwa kiwango cha kutufanya tujisikie vizuri. Maisha ya kweli hayawezi tu kuwa ni muundo unotokana n vile tutakavyo, na hatari au usalama wa matakwa yetu utatokana tu na vile tulivyo kama watu wakomavu, hatuwezi kuipuuzia hali yoyote tuliyonayo na wala si vema kuwa wapuuziaji na tena ni busara kutoruhusu aina yoyote ya injili inayojaribu kutuingizia hali ya upuuziaji juu ya kanisa la Mungu.

Imani ya kweli haiwezi kuzalisha mtizamo kinyume cha hali halisi inayolikabili kanisa la leo. Bwana Mungu hajawahi kupuuzia hali na chochote kilichopo, maana hata kile kinachoonekana kama upuuzi machoni pa watu, kwa sababu tu kipo. Yupo aliyekifanya kuwepo kwa faida ya vilivyopo na ndiye anayeruhusu kiendelee kuwepo. Si kwa sababu ya upuuzi ule bali zaidi sana ni kwa sababu ya shabah, busara na mantiki za kusudi la uwepo wa vilivyopo.

Mambo yanaweza kuendelea jinsi yalivyo mpaka yatakapofikia ukomo wa kuwa vile yalivyokuwa na hi ni kwa ajili ya vile yatakiwavyo kuwa hatimae. Na hatuwezi kuzibadili hali na namna toka vile zilizyo bila kukutana na majira yaliyobeba hali na namna za kimabadiliko zinazotokana na asili ya mambo na vyanzo vya uwepo wa yaliyopo. Kwa kusema hivi tunamaanisha kuziona ruhusa za kimbingu juu ya kanisa la Mungu mahala pote. Na huu ni waraka kwa kanisa la ulimwengu, ambao umebeba taarifa mbalimbali muhimu kuhusu maisha na uhai, kuhusu Mungu na ushahihi wa mambo. 







